name: Build AWS-Identity Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-identity-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - run: |
          docker build --no-cache -t ghcr.io/acorn-io/amazon-eks-pod-identity-webhook:${{github.ref_name}} .
          docker push ghcr.io/acorn-io/amazon-eks-pod-identity-webhook:${{github.ref_name}}
        
